// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojpktmqthcvhxrawkeup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qcGt0bXF0aGN2aHhyYXdrZXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MTI0NjYsImV4cCI6MjA1NjQ4ODQ2Nn0.hng1tROa-PrMLQbcRpRjFomJXIY79rrmiPS7ihpivPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);